version: "3.8"
services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80" # Port HTTP untuk publik & verifikasi SSL
      - "81:81" # Port Dashboard Admin NPM
      - "443:443" # Port HTTPS untuk akses aman publik
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt

volumes:
  npm_data:
    driver: local
  npm_letsencrypt:
    driver: local
